plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: /Users/odmishien/.go/src/github.com/odmishien/yarn2_playground/.yarn/releases/yarn-berry.js
